language: node_js
node_js:
  - "10"
cache: npm
install:
  - npm ci
jobs:
  include:
    - stage: tests
    - script:
      - npm run test:unit
      - npm run test:src
      - npm run lint:check
      - npm run build
